import type { Metadata } from "next";
import "~/app/home/components/header";
import Header from "~/app/home/components/header";
import ChatManager from "./components/chat-manager";
import ChatDetail from "./components/chat_details";

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Header>
        {children}
    </Header>
  );
}
